name: Deploy Build to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Install dependencies
        run: mkdir out/

      - name: Build
        run: touch out/test.html

      - name: Copy build to server
        run: |
          scp -o StrictHostKeyChecking=no -r out/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/html
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
