name: Deploy Build to Server


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install SSH Key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Add server host key to known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # Your other steps here...
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy build to server
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r out/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/html
